# Generated by Django 5.0.4 on 2024-04-20 07:25

import news_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to=news_app.models.upload_path)),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
