# Generated by Django 5.0.4 on 2024-04-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botconfig',
            options={'verbose_name': 'Налаштування Telegram бота', 'verbose_name_plural': 'Налаштування Telegram ботів'},
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='link',
            field=models.URLField(blank=True, default='це поле буде заповнено автоматично', editable=False, max_length=150, verbose_name='URL-адреса бота'),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='server_url',
            field=models.CharField(help_text="https://<ім'я домену>", max_length=200, verbose_name='URL-адреса вебхуку'),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='tid',
            field=models.CharField(blank=True, default='це поле буде заповнено автоматично', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='title',
            field=models.CharField(blank=True, default='це поле буде заповнено автоматично', editable=False, max_length=100, verbose_name="Ім'я бота"),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='token',
            field=models.CharField(help_text='вставте TOKEN, отриманий від BotFather', max_length=150, verbose_name='TOKEN бота'),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='username',
            field=models.CharField(blank=True, default='це поле буде заповнено автоматично', editable=False, max_length=100),
        ),
    ]
