# Generated by Django 5.0.4 on 2024-04-16 19:08

import ads_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to=ads_app.models.service_ads_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='VacancyAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SellAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='SellAdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=ads_app.models.sell_ads_upload_path)),
                ('sell_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads_app.sellad')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyAdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=ads_app.models.vacancy_ads_apload_path)),
                ('vacancy_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads_app.vacancyad')),
            ],
        ),
    ]
