# Generated by Django 5.0.4 on 2024-04-17 01:12

import ads_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellAdImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=ads_app.models.sell_ads_upload_path)),
            ],
        ),
    ]
