# Generated by Django 5.0.4 on 2024-04-20 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_number', models.IntegerField()),
                ('well', models.BinaryField()),
                ('electricity', models.BinaryField()),
                ('fence', models.BinaryField()),
                ('location', models.TextField(blank=True)),
                ('hectare_area', models.DecimalField(decimal_places=3, max_digits=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
