# Generated by Django 5.0.4 on 2024-04-16 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('fathers_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('photo', models.ImageField(upload_to='')),
                ('phone_number', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
            ],
        ),
        migrations.CreateModel(
            name='LandPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_number', models.IntegerField(max_length=3)),
                ('well', models.BinaryField()),
                ('electricity', models.BinaryField()),
                ('fence', models.BinaryField()),
                ('location', models.TextField(blank=True)),
                ('hectare_area', models.DecimalField(decimal_places=3, max_digits=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='community_app.user')),
            ],
        ),
    ]
